INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());INSERT INTO tb_category(name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRONICS', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COMPUTERS', NOW());
